export default [
  {
    id: 1,
    title: 'SUDO | 最輕薄的耳機',
    proposer: '速度股份有限公司',
    subTitle: '耳機界的頂級規格，以最高CP值打造零噪音之聆聽環境，讓喜歡享受音樂的你有更好的體驗。',
    description: 'SUDO 無線耳機結合各種獨家技術，在任何環境皆清晰無比的通話品質、耐用材質以及舒適貼合的設計，提供您絕對的無線自由。結合 TriPort 技術與 Active EQ 功能的 SoundLink 無線耳機，在任何音量都能呈現清脆震撼的音效。想要帶著音樂隨處走，就要有能夠跟上您腳步的耳機。本產品結合防撞材質、玻璃纖維尼龍和抗腐蝕不鏽鋼，能滿足行動生活中的各種挑戰。',
    targetAmount: 300000,
    raisedAmount: 185700,
    success: false,
    file: './images/headphones.jpg',
    link: '/projects/headphones',
    progress: 60
  },
  {
    id: 2,
    title: '自然香 | 多功效天然蠟燭',
    proposer: '自然香股份有限公司',
    subTitle: '除了是香氛蠟燭，蠟油可以當作按摩油使用，點上蠟燭帶著香氣的溫熱按摩油，滋養疲倦的肌膚。',
    description: '最為經典的花香，佛手柑、檸檬、紫羅蘭與麝香和點綴的香草搭配著玫瑰的香氣，彷彿置身於玫瑰花園中。深濃香氣，伴隨著清爽蘋果、梨、白桃和杏仁的氣泡葡萄酒的氣味，搭配甜而不膩的香草香氣。自然香製作的是可以按摩的蠟燭，蠟油可以當作按摩油使用，在家也可以有SPA級的待遇，點上香氛蠟燭用溫熱的按摩油幫自己按摩，是最暖心的享受！無添加人工防腐劑、硬脂、石蠟、對羥基苯甲酸酯。不做動物實驗，對環境與動物友善，可搭配融蠟燈/蠟燭暖燈做使用。',
    targetAmount: 50000,
    raisedAmount: 13400,
    success: false,
    file: './images/scentedcandle.jpg',
    link: '/projects/scentedcandle',
    progress: 42
  },
  {
    id: 3,
    title: '簡單資活 | 多用途延長線',
    proposer: '簡單資活團隊',
    subTitle: '想固定在哪就貼在哪，六個孔座，滿足日常的所有需求，即便在要插滿電器的地方也游刃有餘。',
    description: '資滋團隊研究了市面上的延長線及消費者常見的困擾，發現日常生活中的些許不便，因此我們設計出了多功用延長線，改善家中的各種小問題，不僅讓空間井然有序，也安全無慮。六個孔座可以滿足日常的所有需求，即便在要插滿電器的地方也游刃有餘。緊緊靠住角落，方便貼牆不凌亂、不折線，延長使用壽命，使用更安心。台灣生產製造，阻燃外殼、過載保護、突波接收、多層防護線材，經歷多次嚴格測試，經得起考驗，才是好的延長線。',
    targetAmount: 200000,
    raisedAmount: 176300,
    success: false,
    file: './images/extensioncord.jpg',
    link: '/projects/extensioncord',
    progress: 68
  },
  {
    id: 4,
    title: '暖日子 | 創新設計月曆',
    proposer: '暖日子團隊',
    subTitle: '結合筆記本和月曆的功用，輕鬆裝訂貼近自己使用習慣的筆記本，讓你在哪裡都能寫好字。',
    description: '簡單幾步驟，輕鬆裝訂貼近自己使用習慣的筆記本。友善環境貼心設計，辦公室產生的A4單面空白廢紙，對摺成A5就能無限補充。便於書寫的裝訂，採用可 180 度攤平書寫的裸背精裝，加上特別加厚的堅固封面，讓你不管在哪裡都能寫好字。手邊如果有正在用的A5筆記本，也可輕鬆放入歸納，型態多樣的內頁，方眼、空白、金句，三種不同功能的內頁設計，獻給生活多彩、文思泉湧的你。',
    targetAmount: 10000,
    raisedAmount: 3900,
    success: false,
    file: './images/calendar.jpg',
    link: '/projects/extensioncord',
    progress: 65
  },
  {
    id: 5,
    title: 'WARMY | 智慧溫控馬克杯',
    proposer: 'WARMY Co., Ltd',
    subTitle: '這是一款可以自由調整喜愛溫度的馬克杯，採用防水觸控按鍵設計，絕對是您辦公居家的最佳夥伴。',
    description: 'WARMY 採用防水觸控按鍵設計，輕觸即可調整到您喜愛的溫度，即時溫度顯示功能，杯中溫度一眼可見，再也不用以身試水溫，每一口都是最佳溫度。用 50W 加熱系統，以及高效率內加熱設計，回溫效率是傳統底盤的 4 倍快，用電效率更有 30% 以上的提升，不只要快還更加省電！我們重視每一位使用者的安全，獨家專利雙重防空燒設計，內含溫度感測器與過溫斷路器，當產生空燒時會自動斷電，WARMY 馬克杯就是要讓您使用超安心。',
    targetAmount: 250000,
    raisedAmount: 94600,
    success: false,
    file: './images/mug.jpg',
    link: '/projects/extensioncord',
    progress: 43
  },
  {
    id: 6,
    title: 'JOJ | 簡約藍芽音響',
    proposer: 'JOJ Co., Ltd',
    subTitle: '小小一台，溫暖好調性的音感，60種多樣搭配，帶給您居家美感和視聽心靈上的小幸福。',
    description: '清新簡約的外觀，內藏有兩個喇叭單體，高音、中音、低音，調音為加強人聲及音質的細膩度，超越小體積所含蘊的聲音，更痛快淋漓的音質感受。藍牙 5.0 搭配可加裝的藍牙天線，訊號更穩定。不管是無線主動式喇叭或是需要有線的被動式喇叭，都可根據自己的喜好來調整低音的量感。反射式音箱設計，低頻有力度、瞬態好、反應迅速，想擺哪裡都可以。',
    targetAmount: 450000,
    raisedAmount: 39700,
    success: false,
    file: './images/speaker.jpg',
    link: '/projects/extensioncord',
    progress: 88
  }
]
